apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: authorization-server
  name: authorization-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authorization-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: authorization-server
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: keyistpassword
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/keyist?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: keyistuser
          image: localhost:5000/keyist-authorization-server:latest
          name: authorization-server
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always