#Some invalid entries
#Valid entry in code
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: client
    spec:
      containers:
        - image: localhost:5000/keyist-client:latest
          name: client
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
